/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cconexao;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author marcos
 */
public class janela_cadastro extends javax.swing.JFrame {

    /**
     * Creates new form janela_cadastro
     */
    public janela_cadastro() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/cconexao/o.png")));
        initComponents();
        nome.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        funcao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nome = new javax.swing.JTextField();
        setor = new javax.swing.JTextField();
        senha = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        sim = new javax.swing.JRadioButton();
        s = new javax.swing.JLabel();
        nao = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        funcao.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        funcao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        funcao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                funcaoKeyPressed(evt);
            }
        });
        getContentPane().add(funcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 257, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Nome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 50, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Senha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 69, 50, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Setor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 124, 50, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Administrador :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 130, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setText("OK");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 110, 40));

        nome.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        nome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomeKeyPressed(evt);
            }
        });
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 21, 257, -1));

        setor.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        setor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                setorKeyPressed(evt);
            }
        });
        getContentPane().add(setor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 257, -1));

        senha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        senha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 260, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("Função");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 60, -1));

        buttonGroup1.add(sim);
        sim.setText("Sim");
        sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simActionPerformed(evt);
            }
        });
        getContentPane().add(sim, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        s.setText("jLabel8");
        getContentPane().add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        buttonGroup1.add(nao);
        nao.setText("Não");
        nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naoActionPerformed(evt);
            }
        });
        getContentPane().add(nao, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cconexao/o.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 280));

        Voltar.setFont(new java.awt.Font("Ubuntu", 3, 13)); // NOI18N
        Voltar.setText("Voltar");
        Voltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 100, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             // TODO add your handling code here:
             if (sim.isSelected()){
                 String a;
            a="S";   
            s.setText(a);
             }else if(nao.isSelected()){                
                 String a;
            a="N";             
                  s.setText(a);

         
                    
             }
          if (nome.getText().equals("")||(senha.getText().equals(""))){
            JOptionPane.showMessageDialog(null,"Usuario ou Senha em branco");
            
        }else{
        acoes ac=new acoes(nome.getText(),senha.getText(),setor.getText(),funcao.getText(),s.getText());
                ac.salvar();
               
               lista l=new lista();
               l.setVisible(true);
                setVisible(false);
                
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
 if (evt.getKeyCode()==evt.VK_ENTER){
                  if (nome.getText().equals("")||(senha.getText().equals(""))){
            JOptionPane.showMessageDialog(null,"Usuario ou Senha em branco");
            
        }else{
       acoes ac=new acoes(nome.getText(),senha.getText(),setor.getText(),funcao.getText(),s.getText());
                ac.salvar();
                setVisible(false);
        }}
    }//GEN-LAST:event_jButton1KeyPressed

    private void nomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeKeyPressed
if (evt.getKeyCode()==evt.VK_ENTER){
    senha.requestFocus();
}




    }//GEN-LAST:event_nomeKeyPressed

    private void setorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_setorKeyPressed
if (evt.getKeyCode()==evt.VK_ENTER){
    jLabel5.requestFocus();
}



        // TODO add your handling code here:
    }//GEN-LAST:event_setorKeyPressed

    private void simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simActionPerformed
 if (sim.isSelected()){
                 String a;
            a="S";             
                  s.setText(a);

         
             }        
    }//GEN-LAST:event_simActionPerformed

    private void funcaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_funcaoKeyPressed
        if (evt.getKeyCode()==evt.VK_ENTER){
            jButton1.requestFocus();
        }

    }//GEN-LAST:event_funcaoKeyPressed

    private void naoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoActionPerformed
        if (nao.isSelected()){
                 String a;
            a="N";             
                  s.setText(a);

         
             }        
    }//GEN-LAST:event_naoActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
       lista l=new lista();
      
       l.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janela_cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Voltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField funcao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton nao;
    private javax.swing.JTextField nome;
    private javax.swing.JLabel s;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTextField setor;
    private javax.swing.JRadioButton sim;
    // End of variables declaration//GEN-END:variables
}
