/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cconexao;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class login extends javax.swing.JFrame {
   Sala_Reuniao enciartexto;
   listareuniao enviartexto;
    /**
     * Creates new form login
     */
    public login() {
        
        initComponents();
        usuario.requestFocus();
        Inserir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        Entrar = new javax.swing.JButton();
        senha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(13, 21, 11));
        jLabel1.setText("Usuario ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 200, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("Senha");
        jLabel2.setBorder(null);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        usuario.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        usuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usuarioKeyPressed(evt);
            }
        });
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 360, 30));

        Entrar.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        Entrar.setText("Entrar");
        Entrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntrarMouseClicked(evt);
            }
        });
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });
        Entrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EntrarKeyPressed(evt);
            }
        });
        getContentPane().add(Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 130, 60));

        senha.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        senha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaActionPerformed(evt);
            }
        });
        senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                senhaKeyPressed(evt);
            }
        });
        getContentPane().add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 180, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cconexao/login__4_-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 60, 340, 310));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 3, 48)); // NOI18N
        jLabel5.setText("Registro de Reuniões");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 780, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
            
          try{        
        Connection con = Conexao.fazconexao();
      String sql= "select *from usuarios where nome=? and senha=?";
            PreparedStatement stmt=con.prepareStatement(sql);
            stmt.setString(1,usuario.getText());
            stmt.setString(2,new String(senha.getPassword()));
       ResultSet rs=stmt.executeQuery();
     
       if(rs.next()){
           JOptionPane.showMessageDialog(null,"Entrando...");
           Sala_Reuniao exibir=new Sala_Reuniao();
             funcao();
       //    exibir.setVisible(true);
           setVisible(false);
       }else{
           JOptionPane.showMessageDialog(null,"Usuario inesistente ");
       }
       stmt.close();
       con.close();
       
       }catch(SQLException e){
           JOptionPane.showMessageDialog(null,"Falha");
       }
        
    }//GEN-LAST:event_EntrarActionPerformed

    
    private void entrar(){
     try{        
        Connection con = Conexao.fazconexao();
      String sql= "select *from usuarios where nome=? and senha=?";
        PreparedStatement stmt=con.prepareStatement(sql);
            stmt.setString(1,usuario.getText());
            stmt.setString(2,new String(senha.getPassword()));
       ResultSet rs=stmt.executeQuery();
       if(rs.next()){
           JOptionPane.showMessageDialog(null,"Entrando...");
           Sala_Reuniao exibir=new Sala_Reuniao();
             funcao();
             funcaoa();
       //   exibir.setVisible(true);
           setVisible(false);
       }else{
           JOptionPane.showMessageDialog(null,"Usuario inesistente ");
       }
       stmt.close();
       con.close();
       
       }catch(SQLException e){
           JOptionPane.showMessageDialog(null,"Falha");
       }
        
}
    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
      
    }//GEN-LAST:event_usuarioActionPerformed

    private void senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaActionPerformed
       
    }//GEN-LAST:event_senhaActionPerformed

    private void EntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EntrarMouseClicked

    private void EntrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntrarKeyPressed
    if (evt.getKeyCode()==evt.VK_ENTER){
        this.entrar();
    }
    }//GEN-LAST:event_EntrarKeyPressed

    private void usuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioKeyPressed
if (evt.getKeyCode()==evt.VK_ENTER){
    senha.requestFocus();
}






    }//GEN-LAST:event_usuarioKeyPressed

    private void senhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_senhaKeyPressed
if (evt.getKeyCode()==evt.VK_ENTER){
    Entrar.requestFocus();
}





    }//GEN-LAST:event_senhaKeyPressed
public void Inserir(){
   // setIconImage(Toolkit.getDefaultToolkit().getImage("/cconexao/png-transparent-computer-icons-login-password-gesture-lock-screen-miscellaneous-silhouette-form.png"));
setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/cconexao/o.png")));
}
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
public void funcao() throws SQLException{
if(enciartexto == null){
    enciartexto=new Sala_Reuniao();
    enciartexto.setVisible(true);
    enciartexto.recebendo(usuario.getText());
    
}else{
    enciartexto.setVisible(true);
    enciartexto.setState(Sala_Reuniao.NORMAL);
    enciartexto.recebendo(usuario.getText());
}
}   

public void funcaoa() throws SQLException{
if(enviartexto == null){
    enviartexto=new listareuniao();
    enviartexto.recebendoo(usuario.getText());
    
}else{
    enviartexto.setVisible(true);
    enviartexto.setState(Sala_Reuniao.NORMAL);
    enviartexto.recebendoo(usuario.getText());

}
}
}   

