/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cconexao;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marcos
 */
public class telan extends javax.swing.JFrame {
 telan enciartexto;
 telan nomes;
 telan prioridades;
 telan datainicios;
 telan horainicios;
 telan horafims;
 telan equipamentos;
 telan salars;
 telan observacaos;
 telan idu;
 listareuniao asss;

    public listareuniao getAsss() {
        return asss;
    }

    public void setAsss(listareuniao asss) {
        this.asss = asss;
    }

    public telan getNomes() {
        return nomes;
    }

    public void setNomes(telan nomes) {
        this.nomes = nomes;
    }

  
    /**
     * Creates new form telan
     */
    public telan(){
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/cconexao/o.png")));
        initComponents();    
        
    
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        as = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        adasdas = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Prioridade = new javax.swing.JTextField();
        prioridade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        equipamento = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        data = new javax.swing.JFormattedTextField();
        horai = new javax.swing.JFormattedTextField();
        horat = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observacao = new javax.swing.JTextArea();
        segundo = new javax.swing.JRadioButton();
        auditorio = new javax.swing.JRadioButton();
        sexto = new javax.swing.JRadioButton();
        sem = new javax.swing.JRadioButton();
        note = new javax.swing.JRadioButton();
        permicao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        as.setText("ID");
        as.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(as, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel1.setText("Nome :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel2.setText("ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel3.setText("Prioridade :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        adasdas.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        adasdas.setText("Data :");
        getContentPane().add(adasdas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel5.setText("Hora De Termino");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel6.setText("Hora De Inicio");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel8.setText("Observação:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        nome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 40, 190, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cconexao/o.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        Prioridade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Prioridade, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 70, 150, 30));

        prioridade.setEditable(false);
        prioridade.setBorder(null);
        getContentPane().add(prioridade, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, 30));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel9.setText("Equipamento :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        equipamento.setEditable(false);
        equipamento.setBorder(null);
        getContentPane().add(equipamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 10, -1));

        jButton1.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        jButton1.setText("Salvar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 100, 50));

        data.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 190, 30));

        horai.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            horai.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(horai, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 140, 30));

        horat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            horat.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(horat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 120, 30));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel10.setText("Sala Reuniao :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        observacao.setColumns(20);
        observacao.setRows(5);
        observacao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(observacao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 480, -1));

        buttonGroup2.add(segundo);
        segundo.setText("2° Andar");
        segundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundoActionPerformed(evt);
            }
        });
        getContentPane().add(segundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        buttonGroup2.add(auditorio);
        auditorio.setText("Auditorio");
        auditorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auditorioActionPerformed(evt);
            }
        });
        getContentPane().add(auditorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        buttonGroup2.add(sexto);
        sexto.setText("6° Andar");
        sexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sextoActionPerformed(evt);
            }
        });
        getContentPane().add(sexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        buttonGroup1.add(sem);
        sem.setText("Sem Necessidade");
        sem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semActionPerformed(evt);
            }
        });
        getContentPane().add(sem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        buttonGroup1.add(note);
        note.setText("Notebook");
        note.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteActionPerformed(evt);
            }
        });
        getContentPane().add(note, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));
        getContentPane().add(permicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 160, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
    
    
    
    
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
     try {
         if (as.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Favor Selecionar Uma Linha Na Tabela");
         }else{
             String msg = "Deseja Realmente Atualizar !?";
             int resp = JOptionPane.showConfirmDialog(null, msg, "Confirmação", JOptionPane.YES_NO_OPTION);
             
             // excluir registro selecionando pelo ID
             if (resp == JOptionPane.YES_OPTION) {
                 try{
                     Connection con =Conexao.fazconexao();
                     String sql="UPDATE alocacao SET NOME=?,PRIORIDADE=?,DATAINICIO=?,HORAINICIO=?,HORAFIM=?,ASSUNTO=?,EQUIPAMENTO=?,SALAREUNIAO=? WHERE ID=?";
                     PreparedStatement stmt=con.prepareStatement(sql);
                     stmt.setString(1,nome.getText());
                     stmt.setString(2,Prioridade.getText());
                     String dia =data.getText().substring(0,2);
                     String mes =data.getText().substring(3,5);
                     String ano =data.getText().substring(6);
                     String my=ano+"-"+mes+"-"+dia;
                     stmt.setObject(3,my);
                     //stmt.setString(3,data.getText());
                     stmt.setString(4,horai.getText());
                     stmt.setString(5,horat.getText());
                     stmt.setString(6,observacao.getText());
                     stmt.setString(7,equipamento.getText());
                     stmt.setString(8,prioridade.getText());
                     stmt.setString(9,as.getText());
                     stmt.execute();
                     stmt.close();
                     con.close();
                     JOptionPane.showMessageDialog(null, "Atualizado!");
                     as.setText("");
                     
                 }catch(SQLException e){
                     e.printStackTrace();
                 }}}
         funcaoa();
         //JFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
         //    Sala_Reuniao a=new Sala_Reuniao();
         //    a.funcaoa();
         //listareuniao b=new listareuniao();
         //  b.relogio();
         // b.setVisible(true);
         
         this.dispose(); 
// TODO add your handling code here
     } catch (SQLException ex) {
         Logger.getLogger(telan.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void funcaoa() throws SQLException {
        if (asss == null) {
            asss = new listareuniao();
            asss.setVisible(true);
            asss.relogio();
            asss.recebendoo(permicao.getText());

        } else {
            asss.setVisible(true);
            asss.setState(Sala_Reuniao.NORMAL);
            asss.recebendoo(permicao.getText());
            asss.relogio();

        }
    }
    private void sextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sextoActionPerformed
         if(sexto.isSelected()){
           prioridade.setText("6° Andar");
           
        }
    }//GEN-LAST:event_sextoActionPerformed

    private void segundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segundoActionPerformed
          if(segundo.isSelected()){
           prioridade.setText("2° Andar");
           
        }
    }//GEN-LAST:event_segundoActionPerformed

    private void auditorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auditorioActionPerformed
        if(auditorio.isSelected()){
           prioridade.setText("Auditorio");
           
        }
    }//GEN-LAST:event_auditorioActionPerformed

    private void noteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteActionPerformed
        
          if (note.isSelected()){
              equipamento.setText("Notebook");
         
          }
        
    }//GEN-LAST:event_noteActionPerformed

    private void semActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semActionPerformed
         if (sem.isSelected()){
              equipamento.setText("Sem Necessidade");
         
          }
    }//GEN-LAST:event_semActionPerformed

    String a;

    public String getA() {
        return a;
    }

    public void setA(String a) {
        this.a = a;
    }
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new telan().setVisible(true);
             
            }
        });
    }
    public void componentes() {
     try {      
         Connection con5 =Conexao.fazconexao();
         String sql5="select * from usuarios where idusuario=? ";
         PreparedStatement stmt5=con5.prepareStatement(sql5);
         stmt5.setString(1,as.getText());
         ResultSet rs5 = stmt5.executeQuery();
         if (rs5.next()){
             nome.setText(rs5.getString("nome"));
             
             
         }
     } catch (SQLException ex) {
         Logger.getLogger(telan.class.getName()).log(Level.SEVERE, null, ex);
     }
               
        
        
        
        
    }
  

    
public void recebendo(String recebe,String nomess,String Prioridades,String datainicios,String horainicios,String horafims,String equipamentos,String salars,String observacaos,String permicao){
        as.setText(recebe);
        nome.setText(nomess);
        Prioridade.setText(Prioridades);
        data.setText(datainicios);
        horai.setText(horainicios);
        horat.setText(horafims);
        equipamento.setText(equipamentos);
        prioridade.setText(salars);
        observacao.setText(observacaos);
        this.permicao.setText(permicao);
      
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Prioridade;
    private javax.swing.JLabel adasdas;
    private javax.swing.JTextField as;
    private javax.swing.JRadioButton auditorio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JFormattedTextField data;
    private javax.swing.JTextField equipamento;
    private javax.swing.JFormattedTextField horai;
    private javax.swing.JFormattedTextField horat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nome;
    private javax.swing.JRadioButton note;
    private javax.swing.JTextArea observacao;
    private javax.swing.JLabel permicao;
    private javax.swing.JTextField prioridade;
    private javax.swing.JRadioButton segundo;
    private javax.swing.JRadioButton sem;
    private javax.swing.JRadioButton sexto;
    // End of variables declaration//GEN-END:variables
}
